### ISSUE TITLE
Homepagina redesign

### ISSUE THREAD

**Issue by JensVanAssche** [JensVanAssche/giftly#8]
- minder boxen, max 1 box
- info tekst korter en/of in faq
- slogan?
- grotere teskt
- niet moeten scrollen

**Comment by Regentix** [comment]
Oude home text: Wij zijn Giftly! Giftly is een nieuwe service die de manier van pakjes kopen gaat veranderen! Je kent wel de momenten, vlak voor kerstmis of een verjaardag, je wil voor iemand een cadeau kopen maar hebt geen idee hebt hoe of wat, waar of wanneer. Die tijden van kopbreken zijn voorbij dankzij Giftly! Bij ons kan je geweldige cadeaus kopen waarvan je ontvanger noch jezelf weet wat erin zit, een dubbele verrassing dus! Cadeaus kunnen gekocht worden op basis van interesses, lokale of exotische afkomst of gewoon totaal willekeurig!
